version: "3"

services:
    frontend:
        image: hnginterndevfront
        container_name: frontendpage
        ports:
          - 3000:3000
        depends_on:
          - backend

    backend:
        image: hnginterndevback
        container_name: backend
        command: python manage.py runserver 0.0.0.0:8005
        ports:
            - "8005:8005"
networks:
  default:
  name:
  external:
